function out1 = d2(x,y,z)
%D2
%    OUT1 = D2(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    14-Nov-2018 05:04:06

t2 = x.^2;
t3 = y.^2;
t4 = t2+t3;
t5 = sqrt(t4);
t6 = sqrt(2.0);
t7 = z.*2.0e1;
t8 = t5.*2.0e1;
t9 = z.^2;
t14 = t5.*z.*2.0;
t10 = -t2-t3+t7+t8-t9-t14-5.0e1;
t11 = sqrt(t10);
t12 = t5.*t6.*(1.0./2.0);
t13 = t6.*5.0;
t15 = -t2-t3+t7-t8-t9+t14-5.0e1;
t16 = sqrt(t15);
out1 = [t12+t13-t6.*t11.*(1.0./2.0)-t6.*z.*(1.0./2.0);t12+t13+t6.*t11.*(1.0./2.0)-t6.*z.*(1.0./2.0);-t12+t13-t6.*t16.*(1.0./2.0)-t6.*z.*(1.0./2.0);-t12+t13+t6.*t16.*(1.0./2.0)-t6.*z.*(1.0./2.0)];
