function theta1 = theta1(x,y)
%THETA1
%    THETA1 = THETA1(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    14-Nov-2018 03:08:49

t2 = x.*1i;
t3 = t2+y;
t4 = angle(t3);
theta1 = [t4;t4-pi];
