function theta1 = theta1(d2,x,y)
%THETA1
%    THETA1 = THETA1(D2,X,Y)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    14-Nov-2018 05:04:06

theta1 = angle(x.*1i+y)-pi.*(d2./abs(d2)-1.0).*(1.0./2.0);
