function theta3 = theta3(d2,x,y,z)
%THETA3
%    THETA3 = THETA3(D2,X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    14-Nov-2018 05:04:06

theta3 = angle(z.*1i+sqrt(2.0).*d2.*(-5.0e-1+5.0e-1i)+(d2.*sqrt(x.^2+y.^2))./abs(d2)-1.0e1i);
